[package]
name = "etcd2-aws-cluster"
version = "0.1.0"
authors = ["Karl Lam <karl.v.lam@gmail.com>"]

[dependencies]
hyper = "0.10.5"
serde = "0.9.10"
serde_json = "0.9.8"
serde_derive = "0.9.10"
rusoto = {version="0.23.0", features = ["autoscaling", "ec2"]}
